---
title: "robustness"
author: "Changchao Li"
date: "2022/2/16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(igraph)
library(ggplot2)
library(ggsci)

```


##读取网络邻接矩阵，数值“1”表示微生物 OTU 之间存在互作，“0”表示无互作
```{r}

adj1 <- read.csv('n1_matrix0_1.csv', row.names = 1, check.names = FALSE)
adj2 <- read.csv('n2_matrix0_1.csv', row.names = 1, check.names = FALSE)
adj3 <- read.csv('n3_matrix0_1.csv', row.names = 1, check.names = FALSE)
adj4 <- read.csv('n4_matrix0_1.csv', row.names = 1, check.names = FALSE)
adj5 <- read.csv('n5_matrix0_1.csv', row.names = 1, check.names = FALSE)
adj6 <- read.csv('n6_matrix0_1.csv', row.names = 1, check.names = FALSE)

```


#建立函数计算自然连通度
#adj_matrix 是网络邻接矩阵
```{r}

nc <- function(adj_matrix) {
  #获取 0-1 矩阵，1 表示节点间存在边，0 表示不存在边
  adj_matrix <- as.matrix(adj_matrix)
  adj_matrix[abs(adj_matrix) != 0] <- 1
  
  #矩阵的特征分解，获取特征值 λ
  lambda <- eigen(adj_matrix, only.values = TRUE)$values
  lambda <- sort(lambda, decreasing = TRUE)
  
  #计算“平均特征根”，获得自然连通度
  lambda_sum <- 0
  N = length(lambda)
  for (i in 1:N) lambda_sum = lambda_sum + exp(lambda[i])
  lambda_average <- log(lambda_sum/N, base = exp(1))
  lambda_average
}

```


#计算自然连通度
```{r}

natural_connectivity1 <- nc(adj1)
natural_connectivity2 <- nc(adj2)
natural_connectivity3 <- nc(adj3)
natural_connectivity4 <- nc(adj4)
natural_connectivity5 <- nc(adj5)
natural_connectivity6 <- nc(adj6)

```




#转化为 igraph 邻接列表，计算平均度
```{r}

g1 <- graph_from_adjacency_matrix(as.matrix(adj1), mode = 'undirected', diag = FALSE)
g2 <- graph_from_adjacency_matrix(as.matrix(adj2), mode = 'undirected', diag = FALSE)
g3 <- graph_from_adjacency_matrix(as.matrix(adj3), mode = 'undirected', diag = FALSE)
g4 <- graph_from_adjacency_matrix(as.matrix(adj4), mode = 'undirected', diag = FALSE)
g5 <- graph_from_adjacency_matrix(as.matrix(adj5), mode = 'undirected', diag = FALSE)
g6 <- graph_from_adjacency_matrix(as.matrix(adj6), mode = 'undirected', diag = FALSE)


average_degree1 <- mean(degree(g1))
average_degree2 <- mean(degree(g2))
average_degree3 <- mean(degree(g3))
average_degree4 <- mean(degree(g4))
average_degree5 <- mean(degree(g5))
average_degree6 <- mean(degree(g6))

```



##随机去除一定比例的节点计算去除节点后的网络自然连通度及平均度
```{r}

for (i in c(0.5, 0.4, 0.3, 0.2, 0.1)){
  remove_node1 <- sample(1:nrow(adj1), i*nrow(adj1))
  adj1_remove <- adj1[-remove_node1,-remove_node1]
  natural_connectivity1 <- c(natural_connectivity1, nc(adj1_remove))
  g1 <- graph_from_adjacency_matrix(as.matrix(adj1_remove), mode = 'undirected', diag = FALSE)
  average_degree1 <- c(average_degree1, mean(degree(g1)))
}

  

for (i in c(0.5, 0.4, 0.3, 0.2, 0.1)){
  remove_node2 <- sample(1:nrow(adj2),  i*nrow(adj2))
  adj2_remove <- adj2[-remove_node2,-remove_node2]
  natural_connectivity2 <- c(natural_connectivity2, nc(adj2_remove))
  g2 <- graph_from_adjacency_matrix(as.matrix(adj2_remove), mode = 'undirected', diag = FALSE)
  average_degree2 <- c(average_degree2, mean(degree(g2)))
}  



for (i in c(0.5, 0.4, 0.3, 0.2, 0.1)){
  remove_node3 <- sample(1:nrow(adj3),  i*nrow(adj3))
  adj3_remove <- adj3[-remove_node3,-remove_node3]
  natural_connectivity3 <- c(natural_connectivity3, nc(adj3_remove))
  g3 <- graph_from_adjacency_matrix(as.matrix(adj3_remove), mode = 'undirected', diag = FALSE)
  average_degree3 <- c(average_degree3, mean(degree(g3)))
}    



for (i in c(0.5, 0.4, 0.3, 0.2, 0.1)){
  remove_node4 <- sample(1:nrow(adj4),  i*nrow(adj4))
  adj4_remove <- adj4[-remove_node4,-remove_node4]
  natural_connectivity4 <- c(natural_connectivity4, nc(adj4_remove))
  g4 <- graph_from_adjacency_matrix(as.matrix(adj4_remove), mode = 'undirected', diag = FALSE)
  average_degree4 <- c(average_degree4, mean(degree(g4)))
} 



for (i in c(0.5, 0.4, 0.3, 0.2, 0.1)){
  remove_node5 <- sample(1:nrow(adj5), i*nrow(adj5))
  adj5_remove <- adj5[-remove_node5,-remove_node5]
  natural_connectivity5 <- c(natural_connectivity5, nc(adj5_remove))
  g5 <- graph_from_adjacency_matrix(as.matrix(adj5_remove), mode = 'undirected', diag = FALSE)
  average_degree5 <- c(average_degree5, mean(degree(g5)))
} 




for (i in c(0.5, 0.4, 0.3, 0.2, 0.1)){
  remove_node6 <- sample(1:nrow(adj6), i*nrow(adj6))
  adj6_remove <- adj6[-remove_node6,-remove_node6]
  natural_connectivity6 <- c(natural_connectivity6, nc(adj6_remove))
  g6 <- graph_from_adjacency_matrix(as.matrix(adj6_remove), mode = 'undirected', diag = FALSE)
  average_degree6 <- c(average_degree6, mean(degree(g6)))
}  

```



```{r}

dat1 <- data.frame(remove_node = rep(c(0, 50, 40, 30, 20, 10), 2),
                     variable = c(rep('natural_connectivity', 6), rep('average_degree', 6)),
                     values = c(natural_connectivity1, average_degree1),
                   Salinity = rep('0.81', 12), Network = rep('n1',12))


dat2 <- data.frame(remove_node = rep(c(0, 50, 40, 30, 20, 10), 2),
                   variable = c(rep('natural_connectivity', 6), rep('average_degree', 6)),
                   values = c(natural_connectivity2, average_degree2),
                   Salinity = rep('2.14', 12), Network = rep('n2',12))



dat3 <- data.frame(remove_node = rep(c(0, 50, 40, 30, 20, 10), 2),
                   variable = c(rep('natural_connectivity', 6), rep('average_degree', 6)),
                   values = c(natural_connectivity3, average_degree3),
                   Salinity = rep('4.95', 12), Network = rep('n3',12))




dat4 <- data.frame(remove_node = rep(c(0, 50, 40, 30, 20, 10), 2),
                   variable = c(rep('natural_connectivity', 6), rep('average_degree', 6)),
                   values = c(natural_connectivity4, average_degree4),
                   Salinity = rep('12.13', 12), Network = rep('n4',12))




dat5 <- data.frame(remove_node = rep(c(0, 50, 40, 30, 20, 10), 2),
                   variable = c(rep('natural_connectivity', 6), rep('average_degree', 6)),
                   values = c(natural_connectivity5, average_degree5),
                   Salinity = rep('16.31', 12), Network = rep('n5',12))



dat6 <- data.frame(remove_node = rep(c(0, 50, 40, 30, 20, 10), 2),
                   variable = c(rep('natural_connectivity', 6), rep('average_degree', 6)),
                   values = c(natural_connectivity6, average_degree6),
                   Salinity = rep('20.76', 12), Network = rep('n6',12))



dat <- rbind(dat1, dat2, dat3, dat4, dat5, dat6)

write.csv(dat, 'robustness.csv', row.names = FALSE, quote = FALSE)

```


